# Generated by Django 6.0.6 on 2026-06-17 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=30, verbose_name='Country Name')),
            ],
        ),
        migrations.CreateModel(
            name='FurnitureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=30, verbose_name='Furniture Category')),
                ('cat_picture', models.ImageField(upload_to='photos', verbose_name='Furniture Image')),
                ('cat_desc', models.TextField(verbose_name='Furniture Description')),
                ('category_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_typename', models.CharField(choices=[('user', 'USER'), ('buyer', 'BUYER'), ('seller', 'SELLER'), ('rent', 'RENT')], max_length=10, verbose_name='Select User Type')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=30, verbose_name='State Name')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='marketplace.country', verbose_name='Country ID')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30, verbose_name='City Name')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.state', verbose_name='State ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=30, verbose_name='User Name')),
                ('u_dp', models.ImageField(upload_to='photos', verbose_name='User Image')),
                ('u_gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], verbose_name='User Gender')),
                ('u_email', models.EmailField(max_length=30, verbose_name='User Email')),
                ('u_phone', models.CharField(max_length=10, verbose_name='User Phone')),
                ('u_status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], verbose_name='User Status')),
                ('u_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.role', verbose_name='User Type')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_title', models.CharField(max_length=30, verbose_name='Feedback Title')),
                ('f_description', models.TextField(verbose_name='Feedback Description')),
                ('f_on', models.DateTimeField(auto_now_add=True, verbose_name='Feedback On')),
                ('f_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.user', verbose_name='Feedback By')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=30, verbose_name='Complaint Name')),
                ('c_detail', models.TextField(verbose_name='Complaint Description')),
                ('c_photo', models.ImageField(upload_to='photos', verbose_name='Upload Image')),
                ('c_on', models.DateTimeField(auto_now_add=True, verbose_name='Complaint On')),
                ('c_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.user', verbose_name='Complaint By')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=30, verbose_name='Building Name')),
                ('street_name', models.CharField(max_length=30, verbose_name='Street Name')),
                ('city_name', models.CharField(max_length=30, verbose_name='City Name')),
                ('pin_code', models.CharField(max_length=30, verbose_name='Pin Code')),
                ('user_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.user', verbose_name='User Address')),
            ],
        ),
    ]
