# Generated by Django 6.0.6 on 2026-06-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='user_typename',
            field=models.CharField(choices=[('user', 'User'), ('buyer', 'Buyer'), ('seller', 'Seller'), ('rent', 'Rent')], max_length=10, verbose_name='Select User Type'),
        ),
    ]
