# Generated by Django 6.0.6 on 2026-06-18 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_role_user_typename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('brand_description', models.TextField()),
                ('brand_logo', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='NewFurniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200, verbose_name='Furniture Name')),
                ('furniture_description', models.TextField()),
                ('furniture_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('furniture_image', models.ImageField(upload_to='photos')),
                ('available_quantity', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')])),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.brand')),
                ('furniture_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.furniturecategory')),
            ],
        ),
        migrations.CreateModel(
            name='NewFurnitureBuying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_datetime', models.DateTimeField(auto_now_add=True)),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.newfurniture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.user')),
            ],
        ),
        migrations.CreateModel(
            name='OldFurniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_furniture_name', models.CharField(max_length=200)),
                ('old_furniture_description', models.TextField()),
                ('old_furniture_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_furniture_image', models.ImageField(upload_to='photos')),
                ('available_quantity', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')])),
                ('old_furniture_brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.brand')),
                ('old_furniture_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.furniturecategory')),
            ],
        ),
        migrations.CreateModel(
            name='OldFurnitureBuying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldbooking_datetime', models.DateTimeField(auto_now_add=True)),
                ('oldfurniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.oldfurniture')),
                ('userbooking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.user')),
            ],
        ),
        migrations.CreateModel(
            name='RentFurniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentfurniture_name', models.CharField(max_length=200)),
                ('rentfurniture_description', models.TextField()),
                ('rentfurniture_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rentfurniture_image', models.ImageField(upload_to='photos')),
                ('available_quantity', models.IntegerField()),
                ('rentbrand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.brand')),
                ('rentfurniture_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.furniturecategory')),
            ],
        ),
        migrations.CreateModel(
            name='RentFurnitureOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_startdate', models.DateField()),
                ('rent_enddate', models.DateField()),
                ('rent_bookdatetime', models.DateTimeField(auto_now_add=True)),
                ('rent_furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.rentfurniture')),
                ('rent_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.user')),
            ],
        ),
    ]
