# Generated by Django 6.0.6 on 2026-06-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_brand_newfurniture_newfurniturebuying_oldfurniture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oldfurniturebuying',
            old_name='oldbooking_datetime',
            new_name='old_booking_datetime',
        ),
        migrations.RenameField(
            model_name='oldfurniturebuying',
            old_name='oldfurniture',
            new_name='old_furniture',
        ),
        migrations.RenameField(
            model_name='oldfurniturebuying',
            old_name='userbooking',
            new_name='user_booking',
        ),
        migrations.RenameField(
            model_name='rentfurniture',
            old_name='rentbrand_name',
            new_name='rent_brand_name',
        ),
        migrations.RenameField(
            model_name='rentfurniture',
            old_name='rentfurniture_description',
            new_name='rent_furniture_description',
        ),
        migrations.RenameField(
            model_name='rentfurniture',
            old_name='rentfurniture_image',
            new_name='rent_furniture_image',
        ),
        migrations.RenameField(
            model_name='rentfurniture',
            old_name='rentfurniture_name',
            new_name='rent_furniture_name',
        ),
        migrations.RenameField(
            model_name='rentfurniture',
            old_name='rentfurniture_price',
            new_name='rent_furniture_price',
        ),
        migrations.RenameField(
            model_name='rentfurniture',
            old_name='rentfurniture_type',
            new_name='rent_furniture_type',
        ),
        migrations.RenameField(
            model_name='rentfurnitureorder',
            old_name='rent_bookdatetime',
            new_name='rent_book_datetime',
        ),
        migrations.RenameField(
            model_name='rentfurnitureorder',
            old_name='rent_enddate',
            new_name='rent_end_date',
        ),
        migrations.RenameField(
            model_name='rentfurnitureorder',
            old_name='rent_startdate',
            new_name='rent_start_date',
        ),
        migrations.AlterField(
            model_name='rentfurniture',
            name='available_quantity',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')]),
        ),
    ]
