# Generated by Django 6.0.6 on 2026-06-15 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=100, verbose_name="Actor's Name")),
                ('a_profile', models.ImageField(upload_to='photos', verbose_name="Actor's Image")),
                ('a_bio', models.TextField(verbose_name="Actor's Bio")),
                ('a_nationality', models.CharField(max_length=100, verbose_name="Actor's Nationality")),
                ('a_awards', models.CharField(max_length=255, verbose_name="Actor's Awards")),
                ('a_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name="Actor's Gender")),
                ('a_birthdate', models.DateField(verbose_name="Actor's Birthdate")),
                ('a_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.city', verbose_name="Actor's City")),
                ('a_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.country', verbose_name="Actor's Country")),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=100, verbose_name="Director's Name")),
                ('d_image', models.ImageField(upload_to='photos', verbose_name="Director's Image")),
                ('d_bio', models.TextField(verbose_name="Director's Bio")),
                ('d_nationality', models.CharField(max_length=100, verbose_name="Director's Nationality")),
                ('d_awards', models.CharField(max_length=255, verbose_name="Director's Awards")),
                ('d_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name="Director's Gender")),
                ('d_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.city', verbose_name="Director's City")),
                ('d_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.country', verbose_name="Director's Country")),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_year', models.IntegerField()),
                ('trailer', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actors', models.ManyToManyField(to='movies.actor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.category')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.director')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.country')),
            ],
        ),
        migrations.AddField(
            model_name='director',
            name='d_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.state', verbose_name="Director's State"),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.state'),
        ),
        migrations.AddField(
            model_name='actor',
            name='a_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.state', verbose_name="Actor's State"),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=100, verbose_name="User's Name")),
                ('u_profile', models.ImageField(upload_to='photos', verbose_name="User's Image")),
                ('u_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name="User's Gender")),
                ('u_email', models.EmailField(max_length=254, unique=True, verbose_name="User's Email")),
                ('u_phone', models.CharField(max_length=15, verbose_name="User's Phone")),
                ('u_status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name="User's Status")),
                ('u_date_joined', models.DateField(auto_now_add=True, verbose_name="User's Date Joined")),
                ('u_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.city', verbose_name="User's City")),
                ('u_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.country', verbose_name="User's Country")),
                ('u_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.state', verbose_name="User's State")),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.user')),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.user')),
            ],
        ),
    ]
