# Generated by Django 6.0.6 on 2026-06-10 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('runs', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('hundreds', models.IntegerField()),
                ('fifties', models.IntegerField()),
                ('jersey_no', models.IntegerField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypp.playercategory')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypp.playerteam')),
            ],
        ),
    ]
