# Generated by Django 6.0.6 on 2026-06-19 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=20, verbose_name='Country Name')),
            ],
        ),
        migrations.CreateModel(
            name='GadgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=20, verbose_name='Gadget Category')),
                ('cat_picture', models.ImageField(upload_to='photos', verbose_name='Category Image')),
                ('cat_description', models.TextField(verbose_name='Category Description')),
                ('category_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('user', 'User'), ('buyer', 'Buyer'), ('seller', 'Seller'), ('rent', 'Rent')])),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=11, verbose_name='User Name')),
                ('u_dp', models.ImageField(upload_to='photos')),
                ('u_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], verbose_name='User Gender')),
                ('u_email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('u_phone', models.CharField(max_length=10, verbose_name='User Phone')),
                ('u_type', models.CharField(choices=[('user', 'User'), ('buyer', 'Buyer'), ('seller', 'Seller'), ('rent', 'Rent')], verbose_name='User Type')),
                ('u_status', models.CharField(choices=[('0', 'Active'), ('1', 'Inactive')], verbose_name='User Status')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=20, verbose_name='State Name')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.country', verbose_name='Country ID')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20, verbose_name='City Name')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.state', verbose_name='State ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=20, verbose_name='Building Name')),
                ('street_name', models.CharField(max_length=20, verbose_name='Street Name')),
                ('pincode', models.CharField(max_length=20, verbose_name='PINCODE')),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.city', verbose_name='City Name')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.userdetail', verbose_name='User ID')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_title', models.CharField(max_length=20, verbose_name='Feedback Title')),
                ('f_description', models.TextField(verbose_name='Feedback Description')),
                ('f_on', models.DateTimeField(auto_now_add=True, verbose_name='Feedback On')),
                ('f_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.userdetail', verbose_name='Feedback By')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=20, verbose_name='Complaint Name')),
                ('c_details', models.TextField(verbose_name='Complaint Details')),
                ('c_photo', models.ImageField(upload_to='photos', verbose_name='Complaint Photo')),
                ('c_on', models.DateTimeField(auto_now_add=True, verbose_name='Complaint On')),
                ('c_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.userdetail', verbose_name='Complaint By')),
            ],
        ),
    ]
