# Generated by Django 6.0.6 on 2026-06-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='photos')),
                ('total_books', models.IntegerField()),
                ('famous_book', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('crime', 'Crime'), ('drama', 'Drama'), ('thriller', 'Thriller'), ('action', 'Action'), ('comedy', 'Comedy'), ('horror', 'Horror')], max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
