# Generated by Django 6.0.6 on 2026-06-25 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=20, verbose_name='Category Name')),
                ('cat_picture', models.ImageField(upload_to='photos', verbose_name='Category Image')),
                ('cat_description', models.TextField(verbose_name='Category Description')),
                ('category_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=20, verbose_name='County Name')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_typename', models.CharField(choices=[('USER', 'User'), ('BUYER', 'Buyer'), ('RENT', 'Rent')], verbose_name='User Type')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=20, verbose_name='State Name')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.country', verbose_name='County')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20, verbose_name='City Name')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.state', verbose_name='State')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=20, verbose_name='User Name')),
                ('u_dp', models.ImageField(upload_to='photos', verbose_name='User Image')),
                ('u_gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], verbose_name='Gender')),
                ('u_email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('u_phone', models.CharField(max_length=10, verbose_name='User Phone')),
                ('u_status', models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], verbose_name='User Status')),
                ('u_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.role', verbose_name='User Type')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=50, verbose_name='Building Name')),
                ('street_name', models.CharField(max_length=100, verbose_name='Street Name')),
                ('pin_code', models.CharField(max_length=20, verbose_name='Pin Code')),
                ('city_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.city', verbose_name='City')),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.userdetails', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_title', models.CharField(max_length=20, verbose_name='Feedback Title')),
                ('f_description', models.TextField(verbose_name='Feedback Description')),
                ('f_on', models.DateTimeField(auto_now_add=True, verbose_name='Feedback On')),
                ('f_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.userdetails', verbose_name='Feedback By')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=20, verbose_name='Complaint Name')),
                ('c_detail', models.TextField(verbose_name='Complaint Description')),
                ('c_photo', models.ImageField(upload_to='photos', verbose_name='Complaint Image')),
                ('c_on', models.DateTimeField(auto_now_add=True, verbose_name='Complaint On')),
                ('c_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.userdetails', verbose_name='Complaint By')),
            ],
        ),
    ]
