# Generated by Django 6.0.6 on 2026-06-09 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hospital',
            new_name='Patients',
        ),
    ]
